// Generated by Xata Codegen 0.27.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "my_profile",
    columns: [
      { name: "greeting", type: "text" },
      { name: "desc_title", type: "text" },
      { name: "desc_content", type: "text" },
      { name: "email", type: "email", unique: true },
      { name: "image", type: "file" },
      { name: "resume", type: "file" },
      { name: "mood", type: "text" },
    ],
  },
  {
    name: "portfolio",
    columns: [
      { name: "title", type: "string", notNull: true, defaultValue: "" },
      { name: "description", type: "text" },
      { name: "url", type: "string" },
      { name: "github_url", type: "string" },
      { name: "image", type: "file" },
      { name: "is_show", type: "bool", defaultValue: "true" },
    ],
  },
  {
    name: "user",
    columns: [
      { name: "username", type: "string", unique: true },
      { name: "password", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type MyProfile = InferredTypes["my_profile"];
export type MyProfileRecord = MyProfile & XataRecord;

export type Portfolio = InferredTypes["portfolio"];
export type PortfolioRecord = Portfolio & XataRecord;

export type User = InferredTypes["user"];
export type UserRecord = User & XataRecord;

export type DatabaseSchema = {
  my_profile: MyProfileRecord;
  portfolio: PortfolioRecord;
  user: UserRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Anjar-Dwi-Hariadi-s-workspace-89dgv4.us-west-2.xata.sh/db/anjarcreative",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
